In [1]:
import numpy as np
#تستخدم في جميع انواع البيانات والاشهر في الارقام

# lec 1:

In [3]:
l = np.array([1,2,3,4,5,"omar"])
t = np.array((1,2,3,4,5),dtype='i')#dtype نحدد ما هو نوع البيانات بداخلها يمكن عدم وضعها

In [4]:
print(l,type(l),l.dtype)
print(t,type(t),t.dtype)

['1' '2' '3' '4' '5' 'omar'] <class 'numpy.ndarray'> <U11
[1 2 3 4 5] <class 'numpy.ndarray'> int32

# lec 2:

In [6]:
#عند تعريف اكثر من بعد يجب ان يحتوي كل بعد على نفس العدد من الارقام
a = np.array([[1,2,3],[4,5,6]])
b = np.array([[[1,2,3],[4,5,6],[7,8,9]],[[-1,-2,-3],[-4,-5,-6],[-7,-8,-9]]]) #هنا تم تعريف مصفوفه بثلاث ابعاد
print(a.ndim,a.dtype)
print(b.ndim,b.dtype)
print(a[1][0],a[1,0])# نفس الشي 
print(b[0][1][2],b[1,0,0])
print("-----------------")
# تعمل على تفصيل المصفوفه بحيث كم مصفوفه وبكل مصفوفه كم مصفوفه وبكل مصفوفه كم عنصر
print(b.shape,b.shape[0],b.shape[1],b.shape[2])
print("-----------------")
print(a.size,a.nbytes)# يوجد العديد من التوابع 
print("-----------------")
c = np.array(3)
print(c,c.ndim)

2 int32
3 int32
4 4
6 -1
-----------------
(2, 3, 3) 2 3 3
-----------------
6 24
-----------------
3 0

# lec 3:

In [8]:
ones = np.ones(2)
zero = np.zeros
print(ones," and ",zero)
print("-----------------")
numbers = np.arange(1,17)# range() تقوم بعمل مصفوفه بارقام تشبه عمل 
print(numbers)
print("-----------------")
#يقوم بخربطه الاعداد
randomNumbers = np.random.permutation(numbers)
print(randomNumbers)
print(np.random.randint(20))
# ننشا ارقام عشوائيه باي بعد نريد
print(np.random.rand(2,5))
print(np.random.randn(5))
print(np.random.random(5))
print("-----------------")
reshape = numbers.reshape(2,2,2,2)
print(reshape)
print(reshape.ndim,reshape.shape)

[1. 1.]  and  <built-in function zeros>
-----------------
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
-----------------
[12  3 14  5 11  4  6 16  2 13  9 15  1  7  8 10]
2
[[0.75032594 0.11810081 0.82947729 0.3842623  0.614497  ]
 [0.4680465  0.26078012 0.61664549 0.89086503 0.80960361]]
[ 0.37191826 -1.01477967 -0.70224992 -0.79107591 -1.1775133 ]
[0.4059584  0.47660092 0.29715967 0.01739333 0.09321059]
-----------------
[[[[ 1  2]
   [ 3  4]]

  [[ 5  6]
   [ 7  8]]]


 [[[ 9 10]
   [11 12]]

  [[13 14]
   [15 16]]]]
4 (2, 2, 2, 2)

# lec 4: Slicing

In [10]:
# a = b[2:3]   b يؤدي الى تغيير في  a اي تغيير في 
# a= b[2:3].copy()   هكذا نحل المشكله
print(numbers)
print(numbers[4:8])
print(numbers[:8])
print(numbers[4:])
print(numbers[::-1])
print(numbers[-1::])
print("jumb: ",numbers[::2]) # يقفز خطوتين 
print("jumb: ",numbers[::-2]) # يقفز خطوتين لكن يعكس المصفوفه

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
[5 6 7 8]
[1 2 3 4 5 6 7 8]
[ 5  6  7  8  9 10 11 12 13 14 15 16]
[16 15 14 13 12 11 10  9  8  7  6  5  4  3  2  1]
[16]
jumb:  [ 1  3  5  7  9 11 13 15]
jumb:  [16 14 12 10  8  6  4  2]

In [11]:
#   اذا كان غير موجودfalse اذا وجد العنصر وtrue  يتحقق اذا كان العنصر موجود او لا لكل عنصر ويضع  
print(numbers == 5)
# يرجع الفهرس الذي فيه عنصر محدد
idx = np.argwhere(numbers ==5)[0][0]
print("The index of 5 is: ",int(idx)+1)

[False False False False  True False False False False False False False
 False False False False]
The index of 5 is:  5

In [12]:
a = np.round(10*np.random.rand(5,5))
print(a)
print("forth row:",a[4,:])
print("3&4 row:",a[3:5,:])
print("reverse:",a[::-1,::-1])
print("2 col & all row:",a[:,1])
a.T # يقلب السطر عامود والعامود سطر

[[ 6. 10.  8.  3.  7.]
 [ 8.  6.  7.  3.  1.]
 [ 2.  8.  1.  1.  4.]
 [ 2. 10.  3.  8.  5.]
 [ 5.  4.  2.  5. 10.]]
forth row: [ 5.  4.  2.  5. 10.]
3&4 row: [[ 2. 10.  3.  8.  5.]
 [ 5.  4.  2.  5. 10.]]
reverse: [[10.  5.  2.  4.  5.]
 [ 5.  8.  3. 10.  2.]
 [ 4.  1.  1.  8.  2.]
 [ 1.  3.  7.  6.  8.]
 [ 7.  3.  8. 10.  6.]]
2 col & all row: [10.  6.  8. 10.  4.]

array([[ 6.,  8.,  2.,  2.,  5.],
       [10.,  6.,  8., 10.,  4.],
       [ 8.,  7.,  1.,  3.,  2.],
       [ 3.,  3.,  1.,  8.,  5.],
       [ 7.,  1.,  4.,  5., 10.]])

# lec 5: linear algebra

In [14]:
import numpy.linalg as la

In [15]:
# حساب المصفوفه العكسيه
print(la.inv(a))
# ترتيب المصفوفه بالنسبه للاعمده
print(a)
print("sort col: ")
print(np.sort(a,axis=0)) # a.sort(a,axis=0)
print("sort row: ")
print(np.sort(a,axis=1)) #a.sort(a,axis=1)

[[-0.17159436  0.18541033  0.12683062 -0.0768168   0.08925117]
 [-0.01858248  0.00759878  0.14416966  0.02106936 -0.05595468]
 [ 0.23127936 -0.07598784 -0.21442387  0.01657917 -0.0768168 ]
 [-0.07267201  0.03343465 -0.12019895  0.13815971  0.02652666]
 [ 0.08331031 -0.09726444 -0.01809892 -0.04241503  0.07985631]]
[[ 6. 10.  8.  3.  7.]
 [ 8.  6.  7.  3.  1.]
 [ 2.  8.  1.  1.  4.]
 [ 2. 10.  3.  8.  5.]
 [ 5.  4.  2.  5. 10.]]
sort col:
[[ 2.  4.  1.  1.  1.]
 [ 2.  6.  2.  3.  4.]
 [ 5.  8.  3.  3.  5.]
 [ 6. 10.  7.  5.  7.]
 [ 8. 10.  8.  8. 10.]]
sort row:
[[ 3.  6.  7.  8. 10.]
 [ 1.  3.  6.  7.  8.]
 [ 1.  1.  2.  4.  8.]
 [ 2.  3.  5.  8. 10.]
 [ 2.  4.  5.  5. 10.]]

# lec 6: more indexing

In [17]:
# slicingالميزه الرئيسيه فيها هي عند التعديل على المصفوفه لا يتم التعديل على المصفوفه القديمه على عكس 
a = np.arange(10)
print(a)
# تعمل على اخذ عناصر محدد من المصفوفه ووضعهم في مصفوفه جديده
print(a[[1,5,9]])
# يجب وضعهم لجميع عناصر المصفوفه
print(a[[True,True,False,True,False,True,True,False,True,False]])
print(a[a<8],a[a==8],a[(a<8)&(a>4)])
#    اذا وجد عنصر فقط  and  تستخدم 
# تستخدم & اذا وجد اكثر من عنصر مصفوفه
# | , or , ~ , not مشابه لما سبق

[0 1 2 3 4 5 6 7 8 9]
[1 5 9]
[0 1 3 5 6 8]
[0 1 2 3 4 5 6 7] [8] [5 6 7]

# lec 7: Broadcasting

In [19]:
print(a)
a = a + 5
print(a)
b = a * a
print(b)

[0 1 2 3 4 5 6 7 8 9]
[ 5  6  7  8  9 10 11 12 13 14]
[ 25  36  49  64  81 100 121 144 169 196]

In [20]:
arr1 = np.round(np.random.rand(2,3)*10)
print(arr1)
arr2 = np.round(np.random.rand(2,2)*10)
print(arr2)
#(tuple)اذا اردنا دمج الاعمدة مصفوفتين يجب استخدامها بشرط ان يكون عدد الاسطر متشابه ويجب ان يكون الدخل 
arr3 = np.hstack((arr1,arr2))
print(arr3)

[[ 9.  2.  6.]
 [ 8. 10.  1.]]
[[2. 0.]
 [4. 2.]]
[[ 9.  2.  6.  2.  0.]
 [ 8. 10.  1.  4.  2.]]

In [21]:
arr4 = np.round(np.random.rand(2,3)*10)
print(arr4)
arr5 = np.round(np.random.rand(3,3)*10)
print(arr5)
# اذا اردنا دمج الاسطر بشرط ان ايكون عدد الاعمده متساوي
arr6 = np.vstack((arr4,arr5))
print(arr6)

[[3. 7. 6.]
 [2. 6. 9.]]
[[7. 2. 6.]
 [4. 0. 2.]
 [7. 2. 9.]]
[[3. 7. 6.]
 [2. 6. 9.]
 [7. 2. 6.]
 [4. 0. 2.]
 [7. 2. 9.]]

In [22]:
#  مقارنه السرعه
b = np.random.rand(10000000)
def summ(d):
    s = 0
    for i in d:
        s += i
    return s
%timeit sum(b)
%timeit np.sum(b)
%timeit sum(b)

760 ms ± 29.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
11.3 ms ± 521 μs per loop (mean ± std. dev. of 7 runs, 100 loops each)
837 ms ± 84.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)

<h1>Pandas</h1>

In [24]:
import pandas as pd
print(pd.__version__)

2.2.2

In [25]:
#  مناسب للبعد الوحيد
#  يمكن وضع اي هيكل بيانات
data = pd.Series([1,2,3,'d',5],index=['a','b','c',4,'e'])
print(data.dtype,type(data))
print(data.values,data.index)
print(data['a'])
#  لكن العنصر الاخير يكون داخل slicingيمكن تطبيق جميع عمليات 
print(data['a':4])

object <class 'pandas.core.series.Series'>
[1 2 3 'd' 5] Index(['a', 'b', 'c', 4, 'e'], dtype='object')
1
a    1
b    2
c    3
4    d
dtype: object

In [26]:
marks_dict = {'A+':4,'A-':3.7,'A':3.5,'B+':3.25,'B':3,'B-':2.7}
print("dict1: ",marks_dict)
marks = pd.Series(marks_dict)
print("series: \n",marks)
marks_dict2 = {'A+':100,'A-':96,'A':94,'B+':90,'B':85,'B-':80,'f':0}
print("dict2: ",marks_dict2)
marks2 = pd.Series(marks_dict2)
print("series: \n",marks2)
print(marks['A+':'B'])
print(marks[0:5])

dict1:  {'A+': 4, 'A-': 3.7, 'A': 3.5, 'B+': 3.25, 'B': 3, 'B-': 2.7}
series:
 A+    4.00
A-    3.70
A     3.50
B+    3.25
B     3.00
B-    2.70
dtype: float64
dict2:  {'A+': 100, 'A-': 96, 'A': 94, 'B+': 90, 'B': 85, 'B-': 80, 'f': 0}
series:
 A+    100
A-     96
A      94
B+     90
B      85
B-     80
f       0
dtype: int64
A+    4.00
A-    3.70
A     3.50
B+    3.25
B     3.00
dtype: float64
A+    4.00
A-    3.70
A     3.50
B+    3.25
B     3.00
dtype: float64

In [27]:
# في القيم الغير موجوده nan اي عامود باسم مختلف وموجود بهيكل وغير موجود بالاخر يضيف العامود والقيم ويضع 
dataframe = pd.DataFrame({'marks':marks,'marks2':marks2})
print(dataframe)
print(dataframe.T)
print(dataframe[0:4])
print("marks: ",dataframe['marks']['A'],dataframe.values[0,0])
print("valuse:\n",dataframe.values)
print("insdex: ",dataframe.index)
print("columns: ",dataframe.columns)

    marks  marks2
A    3.50      94
A+   4.00     100
A-   3.70      96
B    3.00      85
B+   3.25      90
B-   2.70      80
f     NaN       0
           A     A+    A-     B     B+    B-    f
marks    3.5    4.0   3.7   3.0   3.25   2.7  NaN
marks2  94.0  100.0  96.0  85.0  90.00  80.0  0.0
    marks  marks2
A     3.5      94
A+    4.0     100
A-    3.7      96
B     3.0      85
marks:  3.5 3.5
valuse:
 [[  3.5   94.  ]
 [  4.   100.  ]
 [  3.7   96.  ]
 [  3.    85.  ]
 [  3.25  90.  ]
 [  2.7   80.  ]
 [   nan   0.  ]]
insdex:  Index(['A', 'A+', 'A-', 'B', 'B+', 'B-', 'f'], dtype='object')
columns:  Index(['marks', 'marks2'], dtype='object')

In [28]:
#  اضافه عامود جديد
print(dataframe)
dataframe["sum_marks"] = dataframe['marks']+dataframe['marks2']
print(dataframe)

    marks  marks2
A    3.50      94
A+   4.00     100
A-   3.70      96
B    3.00      85
B+   3.25      90
B-   2.70      80
f     NaN       0
    marks  marks2  sum_marks
A    3.50      94      97.50
A+   4.00     100     104.00
A-   3.70      96      99.70
B    3.00      85      88.00
B+   3.25      90      93.25
B-   2.70      80      82.70
f     NaN       0        NaN

In [29]:
#  حذف عامود
del dataframe['sum_marks']
print(dataframe)

    marks  marks2
A    3.50      94
A+   4.00     100
A-   3.70      96
B    3.00      85
B+   3.25      90
B-   2.70      80
f     NaN       0

In [30]:
#  indexing يمكن تطبيق جميع عمليات 
g = dataframe[(dataframe['marks2']>90) & (dataframe['marks2']<100)]
print(g)

    marks  marks2
A     3.5      94
A-    3.7      96

In [31]:
d = pd.Series({'a':10,'b':20})
c = pd.Series({'b':30,'c':40})
pd.DataFrame({'d':d,'c':c})

      d     c
a  10.0   NaN
b  20.0  30.0
c   NaN  40.0

In [32]:
#   NaN معالجه  
#  طريقه ثانيه للتعريف بحيث هنا نحدد كم سطر
d = pd.DataFrame([{'a':10,'b':20},{'b':30,'c':40}])
print(d)
# 1: nan تعمل على ملا الصفوف التيؤ تحتوي على 
d.fillna(10)
# 2: nan تعمل على اسقاط جميع الصفوف التي تحتوي على 
d.dropna()
# 3:   في جميع اعمدته nan تعمل على حذف الصف الذي يحتوي على 
d.dropna(how='all')

      a   b     c
0  10.0  20   NaN
1   NaN  30  40.0

      a   b     c
0  10.0  20   NaN
1   NaN  30  40.0

In [35]:
print(d.index)

Index([1, 3, 5], dtype='int64')

In [33]:
d = pd.Series(['a','b','c'],index=[1,3,5])
print(d)
print(d[1:5])
#  تتحرك حسب الفهرس الذي وضعته
print("loc:")
print(d.loc[1:3])
#  تتحرك حسب الفهرس الذي وضعه النظام ولكن لا تاخذ العنصر الاخير
print("iloc:")
print(d.iloc[0:2])
print(dataframe.iloc[3,:]) #values تشبه عمل 
print(dataframe.iloc[::-1,::-1])

1    a
3    b
5    c
dtype: object
3    b
5    c
dtype: object
loc:
1    a
3    b
dtype: object
iloc:
1    a
3    b
dtype: object
marks      3.0
marks2    85.0
Name: B, dtype: float64
    marks2  marks
f        0    NaN
B-      80   2.70
B+      90   3.25
B       85   3.00
A-      96   3.70
A+     100   4.00
A       94   3.50

In [34]:
df = pd.read_csv('Online Retail.csv')  # قراءه اليبانات
df.head(1)  # عرض العناصر
df.dtypes #  معرفه نوع كل عامود
df.drop(['InvoiceNo','Description'],axis=1)  #inplace=True
df.rename(columns={'InvoiceNo' : 'ID'})  #inplace=True
df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate']) # تعمل على تغير عرض التاريخ
df.describe()  # عرض معلومات عن البيانات
df.info()    # عرض معلومات عن البيانات
z =df.groupby('Country')[['Quantity','Description','UnitPrice','Country']].sum().reset_index()

FileNotFoundError: [Errno 2] No such file or directory: 'Online Retail.csv'

In [ ]:
df.head(5)
df.loc[0:2,'InvoiceNo':'Description']	
df.iloc[0:2,0:4]
df.drop(['InvoiceNo','Description'],axis=1)
df.rename(columns={'InvoiceNo' : 'ID'})

In [ ]:
z =df.groupby('Country')[['Quantity','Description','UnitPrice','Country']].sum().reset_index()

In [ ]:
zbins = [0, 12, 19 , 30, 60, 90]
group = ['child', 'teenager', 'young_adult', 'middle_aged', 'enior_citizen']
stroke_data['age_category'] = pd.cut(stroke_data['age'], bins, labels=group)
# هنا نستخدم الدالة pd.cut لتقسيم قيم العمود 'age' إلى الفئات المحددة في bins، ونعطي كل فئة اسم من labels=group.

In [ ]:
# هي دالة في مكتبة pandas تُستخدم لتحويل البيانات من شكل عريض (wide format) إلى شكل طويل (long format).
data_to_plot = pd.melt(wine_df[['alcohol', 'malic_acid', 'alcalinity_of_ash', 'target']],
                      id_vars='target',
                      var_name='features',
                      value_name='value')

sns.swarmplot(data=data_to_plot, x='features', y='value',hue='target')

- id_vars='target'  
  يخبر الدالة أن هذا العمود (target) هو معرف ثابت، لن يتحول أو يُدمج مع الأعمدة الأخرى، بل سيبقى كما هو في كل صف.

- var_name='features'  
  اسم العمود الجديد الذي سيتم إنشاؤه ليحمل أسماء الخصائص الأصلية (مثل alcohol و malic_acid وغيرها).

- value_name='value'  
  اسم العمود الجديد الذي سيحمل القيم المقابلة لكل خاصية.